name: usesend-smtp-server

services:
  certs:
    image: ldez/traefik-certs-dumper:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
    command:
      - file
      - --watch
      - --version=v2
      - --source=/acme/acme.json
      - --dest=/certs
      - --domain-subdir
      - --crt-name=fullchain
      - --key-name=privatekey
      - --crt-ext=.pem
      - --key-ext=.pem
    volumes:
      - ${ACME_JSON_PATH}:/acme/acme.json:ro
      - certs:/certs

  smtp-server:
    container_name: usesend-smtp-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - certs
    environment:
      SMTP_AUTH_USERNAME: "usesend"
      USESEND_BASE_URL: ${USESEND_BASE_URL}
      USESEND_API_CERT_PATH: ${USESEND_API_CERT_PATH}
      USESEND_API_KEY_PATH: ${USESEND_API_KEY_PATH}
      NODE_ENV: "production"
    volumes:
      - certs:/certs:ro
    ports:
      - "25:25"
      - "587:587"
      - "2587:2587"
      - "465:465"
      - "2465:2465"
    restart: unless-stopped

volumes:
  certs:
